services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokemon-fe-web
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
